// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WordsDoc.Models;

namespace WordsDoc.Migrations
{
    [DbContext(typeof(WordsContext))]
    [Migration("20210127134427_init1")]
    partial class init1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("WordsDoc.Models.DefinisionItem", b =>
                {
                    b.Property<string>("Definition")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DefinisionResponseWord")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PartOfSpeech")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Definition");

                    b.HasIndex("DefinisionResponseWord");

                    b.ToTable("DefinisionItem");
                });

            modelBuilder.Entity("WordsDoc.Models.DefinisionResponse", b =>
                {
                    b.Property<string>("Word")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Word");

                    b.ToTable("DefinisionResponses");
                });

            modelBuilder.Entity("WordsDoc.Models.DefinisionItem", b =>
                {
                    b.HasOne("WordsDoc.Models.DefinisionResponse", null)
                        .WithMany("Definitions")
                        .HasForeignKey("DefinisionResponseWord");
                });

            modelBuilder.Entity("WordsDoc.Models.DefinisionResponse", b =>
                {
                    b.Navigation("Definitions");
                });
#pragma warning restore 612, 618
        }
    }
}
