// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WordsDoc.Models;

namespace WordsDoc.Migrations
{
    [DbContext(typeof(WordsContext))]
    [Migration("20210223055103_init2")]
    partial class init2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("WordsDoc.Models.DefinisionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("DefinisionResponseId")
                        .HasColumnType("int");

                    b.Property<int?>("DefinisionResponseId1")
                        .HasColumnType("int");

                    b.Property<string>("Definition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartOfSpeech")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DefinisionResponseId");

                    b.HasIndex("DefinisionResponseId1");

                    b.ToTable("DefinisionItems");
                });

            modelBuilder.Entity("WordsDoc.Models.DefinisionResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("WordId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DefinisionResponses");
                });

            modelBuilder.Entity("WordsDoc.Models.DefinisionItem", b =>
                {
                    b.HasOne("WordsDoc.Models.DefinisionResponse", null)
                        .WithMany("DefinisionItems")
                        .HasForeignKey("DefinisionResponseId");

                    b.HasOne("WordsDoc.Models.DefinisionResponse", null)
                        .WithMany("Definitions")
                        .HasForeignKey("DefinisionResponseId1");
                });

            modelBuilder.Entity("WordsDoc.Models.DefinisionResponse", b =>
                {
                    b.Navigation("DefinisionItems");

                    b.Navigation("Definitions");
                });
#pragma warning restore 612, 618
        }
    }
}
